// battlezone hooks — generated by server/scripts/build.mjs — do not edit
// 등록 전용 엔트리. 로직은 battlezone-lib.js(CJS) — 각 핸들러 본문 안에서 require.
// PB v0.39 jsvm 실행 VM 재컴파일 대응: 클로저/모듈 전역 참조 금지(함정 #2),
// 엔트리 module.exports 금지(함정 #3).
routerAdd("GET", "/api/v2/admin/debug-table", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/admin/debug-table"](c);
});
routerAdd("GET", "/api/v2/admin/keys/usage", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/admin/keys/usage"](c);
});
routerAdd("GET", "/api/v2/admin/season/rewards", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/admin/season/rewards"](c);
});
routerAdd("GET", "/api/v2/notifications", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/notifications"](c);
});
routerAdd("GET", "/api/v2/party/my", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/party/my"](c);
});
routerAdd("GET", "/api/v2/party/search", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/party/search"](c);
});
routerAdd("GET", "/api/v2/pubg/battles/rounds", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/pubg/battles/rounds"](c);
});
routerAdd("GET", "/api/v2/pubg/keys/usage", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/pubg/keys/usage"](c);
});
routerAdd("GET", "/api/v2/pubg/queue/count", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/pubg/queue/count"](c);
});
routerAdd("GET", "/api/v2/pubg/rankings", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/pubg/rankings"](c);
});
routerAdd("GET", "/api/v2/season/rewards", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/season/rewards"](c);
});
routerAdd("GET", "/api/v2/valorant/queue-status", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/valorant/queue-status"](c);
});
routerAdd("GET", "/api/v2/valorant/rankings", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/valorant/rankings"](c);
});
routerAdd("GET", "/api/v2/valorant/rankings/me", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/valorant/rankings/me"](c);
});
routerAdd("GET", "/api/v2/valorant/rooms/{id}", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/valorant/rooms/{id}"](c);
});
routerAdd("GET", "/api/v2/valorant/settings", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/valorant/settings"](c);
});
routerAdd("GET", "/api/v2/valorant/stats-me", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["GET /api/v2/valorant/stats-me"](c);
});
routerAdd("POST", "/api/v2/admin/drop-orphan-table", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/admin/drop-orphan-table"](c);
});
routerAdd("POST", "/api/v2/admin/keys/test", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/admin/keys/test"](c);
});
routerAdd("POST", "/api/v2/admin/penalty", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/admin/penalty"](c);
});
routerAdd("POST", "/api/v2/admin/room/adjudicate", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/admin/room/adjudicate"](c);
});
routerAdd("POST", "/api/v2/admin/room/{id}/force-end", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/admin/room/{id}/force-end"](c);
});
routerAdd("POST", "/api/v2/admin/season/advance", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/admin/season/advance"](c);
});
routerAdd("POST", "/api/v2/notifications/read", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/notifications/read"](c);
});
routerAdd("POST", "/api/v2/notifications/read-all", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/notifications/read-all"](c);
});
routerAdd("POST", "/api/v2/party/accept", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/accept"](c);
});
routerAdd("POST", "/api/v2/party/create", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/create"](c);
});
routerAdd("POST", "/api/v2/party/decline", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/decline"](c);
});
routerAdd("POST", "/api/v2/party/disband", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/disband"](c);
});
routerAdd("POST", "/api/v2/party/invite", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/invite"](c);
});
routerAdd("POST", "/api/v2/party/kick", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/kick"](c);
});
routerAdd("POST", "/api/v2/party/leave", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/leave"](c);
});
routerAdd("POST", "/api/v2/party/queue-cancel", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/queue-cancel"](c);
});
routerAdd("POST", "/api/v2/party/queue-enter", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/party/queue-enter"](c);
});
routerAdd("POST", "/api/v2/pubg/battles/cancel", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/battles/cancel"](c);
});
routerAdd("POST", "/api/v2/pubg/battles/confirm-start", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/battles/confirm-start"](c);
});
routerAdd("POST", "/api/v2/pubg/battles/forfeit", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/battles/forfeit"](c);
});
routerAdd("POST", "/api/v2/pubg/battles/round-add", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/battles/round-add"](c);
});
routerAdd("POST", "/api/v2/pubg/battles/round-delete", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/battles/round-delete"](c);
});
routerAdd("POST", "/api/v2/pubg/battles/scan", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/battles/scan"](c);
});
routerAdd("POST", "/api/v2/pubg/battles/settle", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/battles/settle"](c);
});
routerAdd("POST", "/api/v2/pubg/lookup", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/lookup"](c);
});
routerAdd("POST", "/api/v2/pubg/matchmaking/run", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/matchmaking/run"](c);
});
routerAdd("POST", "/api/v2/pubg/queue/cancel", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/pubg/queue/cancel"](c);
});
routerAdd("POST", "/api/v2/valorant/lookup", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/lookup"](c);
});
routerAdd("POST", "/api/v2/valorant/queue-cancel", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/queue-cancel"](c);
});
routerAdd("POST", "/api/v2/valorant/queue-enter", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/queue-enter"](c);
});
routerAdd("POST", "/api/v2/valorant/rankings/me/role", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/rankings/me/role"](c);
});
routerAdd("POST", "/api/v2/valorant/rooms/{id}/code", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/rooms/{id}/code"](c);
});
routerAdd("POST", "/api/v2/valorant/rooms/{id}/no-show", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/rooms/{id}/no-show"](c);
});
routerAdd("POST", "/api/v2/valorant/rooms/{id}/report", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/rooms/{id}/report"](c);
});
routerAdd("POST", "/api/v2/valorant/rooms/{id}/start", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/rooms/{id}/start"](c);
});
routerAdd("POST", "/api/v2/valorant/rooms/{id}/verify", function (c) {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.routes["POST /api/v2/valorant/rooms/{id}/verify"](c);
});
cronAdd("bz-auto-verify", "*/2 * * * *", function () {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.crons["bz-auto-verify"].handler();
});
cronAdd("bz-keys-check", "*/10 * * * *", function () {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.crons["bz-keys-check"].handler();
});
cronAdd("bz-maintenance-auto-scan", "*/2 * * * *", function () {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.crons["bz-maintenance-auto-scan"].handler();
});
cronAdd("bz-manner-decay", "0 0 * * *", function () {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.crons["bz-manner-decay"].handler();
});
cronAdd("bz-matchmaking-drain", "* * * * *", function () {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.crons["bz-matchmaking-drain"].handler();
});
cronAdd("bz-penalty-decay", "0 * * * *", function () {
  var L = require(__hooks + "/battlezone-lib.js");
  return L.crons["bz-penalty-decay"].handler();
});
